# Generated by Django 4.1.7 on 2023-03-05 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20230305_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='User',
            field=models.ForeignKey(default=(('main', '0001_initial'),), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
